### ISSUE TITLE
[EPIC] REST layer improvements (post-GA)

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#1452]
- [ ] configurable response types/formats #436
- [ ] serve OpenAPI spec from a controller method
- [ ] etag-based caching
- [ ] Allow controller methods to specify custom status code and contribute additional response headers
- [x] streaming requests
- [ ] streaming responses #2230
- [ ] handling file uploads https://github.com/strongloop/loopback-next/issues/1873
- etc.
