### ISSUE TITLE
Docs: what relation types will work well with my database?

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#2341]
Create a new section (or even a new page) in our docs for relations and explain users what relation type to choose depending on which database they use.·

We should verify that our recommended solution is actually a good one that works well for the target database. This will most likely require research on our side, as we don't have deep knowledge of different NoSQL databases. Such research is out of scope of this story, there will be follow-up spike stories. While creating the first version of the guide, we should simply label the entries that we are not confident about.

_An example for illustration:_

**SQL databases**

Relation type|LoopBack flavor
-|-
1-N|[HasMany](https://loopback.io/doc/en/lb4/HasMany-relation.html)
N-1|[BelongsTo](https://loopback.io/doc/en/lb4/BelongsTo-relation.html)
1-1|[HasOne](https://loopback.io/doc/en/lb4/hasOne-relation.html)

**MongoDB**

Relation type|LoopBack flavor
-|-
1-N|EmbedsMany
N-1|n/a
1-1|EmbedsOne

The suggestions above are an initial proposal. See the spike story #2342 for discussion about which LoopBack relations work best for MongoDB.

**Cloudant & CouchDB**

Relation type|LoopBack flavor
-|-
1-N|ReferencesMany
N-1|n/a
1-1|ReferencesOne

The suggestions above are an initial proposal. See the spike story #2343 for discussion about which LoopBack relations work best for MongoDB.

(etc. for other databases that have an LoopBack official connector)

See the discussion in #2127 to better understand the wider context and also #2340 for related work.

## Acceptance criteria

- [ ] Create a new section (heading level 2) [Relations](https://loopback.io/doc/en/lb4/Relations.html) page.
- For each of the following connectors, add a subsection explaining how to map 1-N/N-1/1-1 relation to LoopBack relation types. Each subsection should be started by a  heading (level 3?) so that TOC is created at the top of the page and URLs can be created to point directly to each database name.

  - [ ] SQL
  - [ ] MongoDB (the spike story to link to: #2342)
  - [ ] Cloudant & CouchDB (the spike story to link to: #2343)
  - [ ] Cassandra (the spike story to link to: #2344)
