### ISSUE TITLE
Execute raw NoSQL queries (e.g. MongoDB)

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#3342]
## Suggestion

As I wrote in https://github.com/strongloop/loopback-next/issues/2807#issuecomment-487590905, it is possible to execute raw SQL queries using the recently introduced `Repository` method `execute`, see https://github.com/strongloop/loopback-next/pull/2681. This works great for SQL connectors.

Unfortunately, this method does not work for MongoDB and possibly for other NoSQL connectors that require more than just a `command` string and `args` array.

We need to find a way how to improve LB4 API, MongoDB connector API or both, to make it easy to execute raw MongoDB commands.

Related code:
- [loopback-datasource-juggler](https://github.com/strongloop/loopback-datasource-juggler/blob/47addd943adfd7ace37cd52d2d4dcbd04ee7c0d8/lib/datasource.js#L2606-L2643) 
- [loopback-connector-mongodb](https://github.com/strongloop/loopback-connector-mongodb/blob/f67d1e5660e875a839b78177eafdbceb97b686ba/lib/mongodb.js#L449-L520)

## Use Cases

- execute `aggregate` query, see https://github.com/strongloop/loopback-next/issues/2807, https://github.com/strongloop/loopback-next/issues/2021

## Examples

```ts
const result = dataSource.execute('MyCollection', 'aggregate', [
    {
        $lookup:{
            .....   
        }
    },
    {   $unwind:"$data" },
    {
        $match:{
            ...
        }
    },
    {
        $lookup:{
            ... 
        }
    },
    {   $unwind:"$LoanRepayment" },
    { $project : { _id: 0} },
    { $out : "tempData" }
  ],
);
```

## Acceptance criteria

- [x] Improve the typedef signatures for `execute` possibly with some overloading on both repository classes in LB4 (#6030) and datasource classes in Juggler (see https://github.com/strongloop/loopback-datasource-juggler/pull/1855)
- [x] Add API docs on repository classes in LB4 (#6030) and datasource classes in Juggler (see https://github.com/strongloop/loopback-datasource-juggler/pull/1855)
- [x] Create a new page about the `execute` method under https://loopback.io/doc/en/lb4/Working-with-data.html. Mention the connectors that supports the `execute` method (see #6047)
- [ ] Add details about `execute` method on relevant pages under https://loopback.io/doc/en/lb4/Database-connectors.html.

    See also https://github.com/strongloop/loopback-next/pull/6047#pullrequestreview-464468459: 
    > This is a good content to be mentioned in "Configuring DataSource" page #6061

- [x] Add tests to ensure raw NoSQL queries are executing as expected for MongoDB (see https://github.com/strongloop/loopback-next/pull/6046)
- [ ] Investigate why the acceptance test is failing for PostgreSQL and fix the problem, see https://github.com/strongloop/loopback-next/pull/6046#discussion_r467788064

**Comment by mdbetancourt** [comment]
did u see these libs?
https://github.com/kofrasa/mingo
