### ISSUE TITLE
[EPIC] How to migrate LB3 clients

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#3954]
_This is a follow-up for #3718 and #3922._

Write content for `docs/site/migration/clients.md` and explain how to migrate LB3 clients using loopback-specific SDKs to LB4.

List of known LB3 SDKs:

 - [ ] [AngularJS (1.x)](https://loopback.io/doc/en/lb3/AngularJS-JavaScript-SDK.html)
 - [ ] [Angular (2+) via loopback-sdk-builder](https://github.com/mean-expert-official/loopback-sdk-builder)
 - [ ] [Android](https://loopback.io/doc/en/lb3/Android-SDK.html)
 - [ ] [iOS](https://loopback.io/doc/en/lb3/iOS-SDK.html)
 - [ ] [Xamarin](https://loopback.io/doc/en/lb3/Xamarin-SDK.html)
 - [ ] [Isomorphic JavaScript](https://loopback.io/doc/en/lb3/LoopBack-in-the-client.html)

**Comment by joschne** [comment]
I would like to bring an idea into the field: [OpenApiTools/openapi-generator](https://github.com/OpenAPITools/openapi-generator) might help with this.

Because I need a substitute for loopback-sdk-builder [I gave it a try](https://github.com/mean-expert-official/loopback-sdk-builder/issues/628#issuecomment-548486409).

In this approach the OpenApiSpecs (explorer/openapi.json) generated by LoopBack 4 figures as a middleman between LoopBack and the generator of SDKs. In consequence we could relay on code maintained by a wider community, supporting more than 50 languages/frameworks, independent from LoopBack but compatible with LoopBack thanks to the OpenAPI Spec standard.

I have no experience with this approach but I think it's worth a consideration...

**Comment by bajtos** [comment]
@joschne thank you for joining the discussion! It has been our intention for a long time to abandon LoopBack-specific client SDKs and rely on Swagger/OpenAPI client code generation instead. As you said:

> we could relay on code maintained by a wider community, supporting more than 50 languages/frameworks, independent from LoopBack but compatible with LoopBack thanks to the OpenAPI Spec standard.

Do you happen to know what's the relation between swagger-codegen and openapi-generator and how they differ from each other?

BTW if you are using Angular, you may want to also try https://github.com/cyclosproject/ng-openapi-gen

> Because I need a substitute for loopback-sdk-builder [I gave it a try](https://github.com/mean-expert-official/loopback-sdk-builder/issues/628#issuecomment-548486409).

This is awesome! Would you like to contribute the instructions described in https://github.com/joschne/loopback-4-ngx-build-sdk to the official LoopBack documentation?

I think there are two pieces of content that will be useful to LoopBack users:
1. How to talk to a LB4 application from Angular - describe how to generate the client using a codegen tool.
2. How to migrate an Angular client from loopback-sdk-builder to the solution described in the step 1 above.

**Comment by joschne** [comment]
@bajtos I'm happy to hear you like the suggested approach. 

I had to pause the migration from lb3 to lb4. Thus, our software is still running on lb3. Chances are high, that in the run of this year we can continue our work on the migration to lb4. If / when we do so, I'm willing to actively contribute to the official LoopBack documentation. Before that my hands are tied.

> Do you happen to know what's the relation between swagger-codegen and openapi-generator and how they differ from each other?

I have no insider information. My decision for openapi-generator is not based on solid ground, but, back in October, it was influenced by:
- [Mirgation guide](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/migration-from-swagger-codegen.md) 
- [Q&A](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/qna.md)

> BTW if you are using Angular, you may want to also try https://github.com/cyclosproject/ng-openapi-gen

Thank you!

> This is awesome! Would you like to contribute the instructions described in https://github.com/joschne/loopback-4-ngx-build-sdk to the official LoopBack documentation?

Please feel free to take everything from my two examples and integrate it in the official LoopBack documentation. May be the second [repo](https://github.com/joschne/loopback4-example-ngx-sdk) could be useful in combination with the existing to-do-app examples.

> I think there are two pieces of content that will be useful to LoopBack users:
> 
> 1. How to talk to a LB4 application from Angular - describe how to generate the client using a codegen tool.
> 2. How to migrate an Angular client from loopback-sdk-builder to the solution described in the step 1 above.

I agree: These are the two pieces needed in the official LoopBack documentation.

**Comment by agnes512** [comment]
Will we cover strong-pubsub*? https://github.com/strongloop/loopback-next/issues/6190
