### ISSUE TITLE
Globalization and localization

### ISSUE THREAD

**Issue by bajtos** [loopbackio/loopback-next#493]
We should start globalizing all string messages used in loopback-next to allow localization. IMO, we should be extracting strings from the original TypeScript sources, not from the transpiled result.

**Things to investigate - must have**
 - [ ] https://github.com/strongloop/strong-globalize/issues/113: how to extract strings from TypeScript
 - [x] https://github.com/strongloop/strong-globalize/issues/114: type definitions for strong-globalize API

 - [ ] how to setup strong-globalize in lerna monorepo - we need to run strong-globalize locally in each package

**Should have**

 - [ ] https://github.com/strongloop/strong-globalize/issues/112: extend strong-globalize to support [template literals](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals) via [tagged template literals](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals)
