### ISSUE TITLE
[Juggler] Migrate Connectors to TypeScript

### ISSUE THREAD

**Issue by kjdelisle** [loopbackio/loopback-next#892]
## Overview

This epic is about migrating all of the connector modules to TypeScript.

Ideally, the connectors should have been migrated to juggler monorepo first, see https://github.com/strongloop/loopback-next/issues/890

When importing existing codebase(s) to the new monorepo, it's important to use `lerna import` ([docs](https://github.com/lerna/lerna#import)) to preserve git history.

## Connectors To Migrate

- [ ] loopback-connector-cassandra
- [ ] loopback-connector-cloudant
- [ ] loopback-connector-couchdb2
- [ ] loopback-connector-dashdb
- [ ] loopback-connector-db2
- [ ] loopback-connector-db2iseries
- [ ] loopback-connector-db2z
- [ ] loopback-connector-grpc
- [ ] loopback-connector-informix
- [ ] loopback-connector-jsonrpc
- [ ] loopback-connector-kv-extreme-scale
- [ ] loopback-connector-kv-redis
- [ ] loopback-connector-mongodb
- [ ] loopback-connector-mqlight
- [ ] loopback-connector-mssql
- [ ] loopback-connector-mysql
- [ ] loopback-connector-oracle
- [ ] loopback-connector-postgresql
- [ ] loopback-connector-remote
- [ ] loopback-connector-rest
- [ ] loopback-connector-soap
- [ ] loopback-connector-swagger
- [ ] loopback-connector-zosconnectee

**Comment by dhmlau** [comment]
FYI - `loopback-connector-zosconnectee` is done by another team.  If we're planning to migrate the connectors to TypeScript, we should let them know - whether it is a must to migrate to TS, what are the consequences if not migrating, etc.

**Comment by coderhaoxin** [comment]
How can outside contributors help with this?

For example, if you guys have set up the mono repository and port exists repositories,
I'll glad to submit PRs to jsonrpc connector at first.

**Comment by virkt25** [comment]
@coderhaoxin PRs from community contributors are welcome! Feel free to open a PR converting the `jsonrpc` connector to TypeScript and we'll be happy to review / get it landed.
